### PR TITLE
Add a checkbox for every item ysync searchs for

### LINKED ISSUE #105: FRP: add a checkbox for every item ysync searchs for
### What is your proposal 🚀
Add a checkbox to inculde exculde all itesm that are currently searched for. Every item should be toggleable off and on. Thus I can set it to only show vault icons errors, and also update the % complete to what is toggled out of all vaults, dont make it static for all items
image

- risk
- risk score
- apy
- price
- strategies
- ledger live
- ... ect

### What does this solve ? 🛠
We can search for only what our team wants to look at.

### More 🔎
*N/A*

### PR DESCRIPTION
**Pull request by karelianpie**
## Description

Add a filter for each and every item that we display, namely:

- Translations
- Icon
- Price
- Retirement
- Yearn Meta File
- Ledger Live
- Strategies
- Risk 
- Risk Score
- Descriptions
- APY
- Want Token Description

## Related Issue

Closes https://github.com/yearn/ySync/issues/105 (partially)

Error rate still for all items

## Motivation and Context

Make it easier for users to find exactly what they want to look at, they can filter for exactly what they need and check for all vaults or just the ones with anomalies.

## How Has This Been Tested?

Tested locally, but @0xBasically could you please test this thoroughly? 🙇 

## Screenshots (if appropriate):

Screenshot_2023-08-03_at_12_55_35

### CODE REVIEW

**Comment by 0xBasically** [comment]
@karelianpie can you check that network switching is smooth and working, requiring a hard refresh locally for me.

**Comment by karelianpie** [comment]
> @karelianpie can you check that network switching is smooth and working, requiring a hard refresh locally for me.

We're fetching a lot of data with the network switch, so thinking if it's just slow. Can you double check please 🙇

**Review by 0xBasically — APPROVED** [review]
lgtm

**Comment by karelianpie** [comment]
> lgtm

Thank you for the review @0xBasically, but we should have waited for @Majorfi's review 😅 

Codewise there were quite a bit of changes, feels a bit risky merging like this

**Comment by Majorfi** [comment]
Let fix the bugs if bugs pop then! Np!

**Comment by 0xBasically** [comment]
> > lgtm
> 
> Thank you for the review @0xBasically, but we should have waited for @Majorfi's review sweat_smile
> 
> Codewise there were quite a bit of changes, feels a bit risky merging like this

yolo was working good for me

**Pull request merged**
