### PR TITLE
feat: Pending state for Ledger plugin

### LINKED ISSUE #74: FRP: Pending state for Ledger plugin
### What is your proposal 🚀
Add a check to Yearn's fork repo to see if the plugin is soon-to-be merged/a pr has been made and a fix is already ready to merge.

### What does this solve ? 🛠
Right now, even if a PR is made and waiting for review, the Ledger Integration field is set to `KO`. This can be confusing over what should be done.
The check should be done based on the main branch of this fork repo: https://github.com/yearn/app-plugin-yearn

### More 🔎
*N/A*

### PR DESCRIPTION
**Pull request by karelianpie**
## Description

Add a `Pending` state for incoming Ledger plugins

## Related Issue

Closes https://github.com/yearn/ySync/issues/74

## Motivation and Context

Right now, even if a PR is made and waiting for review, the Ledger Integration field is set to KO. This can be confusing over what should be done.

## How Has This Been Tested?

Ran locally and saw the `Pending` state being shown for contracts that are in our fork [yearn/app-plugin-yearn)](https://github.com/yearn/app-plugin-yearn) but not yet in [LedgerHQ/app-plugin-yearn](https://github.com/LedgerHQ/app-plugin-yearn) -- refer to the screenshot below

## Screenshots (if appropriate):

Screen_Shot_2022-10-05_at_3_05_57_pm

### CODE REVIEW

**Review by Majorfi — APPROVED** [review]
LGTM ! Well done
@DarkGhost7 I let you check too before merging!

**Review by DarkGhost7 — APPROVED** [review]
lgtm great feature and implementation.

**Comment by DarkGhost7** [comment]
These warnings don't count against the error rate correct?

**Comment by karelianpie** [comment]
> These warnings don't count against the error rate correct?

No, they do not, good call 👍

**Pull request merged**
