### PR TITLE
feat: Validity of protocols' names in strategies

### LINKED ISSUE #66: FRP: Detect is a protocol is missing
### What is your proposal 🚀
This is a request to detect if a protocol is missing that is linked in strategies. For example if it shows up here in the strategy description https://github.com/yearn/ydaemon/blob/main/data/meta/strategies/1/AaveBorrow.json#L13 (any strategy) but doesn't have a corresponding protocol file, then it should show as a ko error on the protocol tab saying file doesn't exist.

### What does this solve ? 🛠
Makes sure we have all the data correctly input
Should show this error for missing protocols
image
on the protocol tab 
image

### PR DESCRIPTION
**Pull request by karelianpie**
## Description

* Add valid and invalid protocols in a new strategies tab
* Fix typo `sufix` -> `suffix`
* Add `ReactElement` type to `prefix` prop

## Related Issue

Closes https://github.com/yearn/ySync/issues/66

## Motivation and Context

Strategies have a `protocols` field which might contain protocols that are not valid

## How Has This Been Tested?

Ran locally and observed the valid and invalid protocol names being shown, refer to the screenshots below

### All Strategies with Protocol Names

Screen Shot 2022-10-01 at 10 17 44 am

### Only Strategies with Protocol Names Anomalies

Screen Shot 2022-10-01 at 10 17 33 am

### CODE REVIEW

**Comment by Majorfi** [comment]
Would it be possible to add a filter `Anomalies only` for the strategies ?
- Checked -> Only display the anomalies
- Unchecked -> Display the anomalies and the good ones

**Comment by DarkGhost7** [comment]
image
Can we delete this (1) I dont see the purpose here

**Comment by DarkGhost7** [comment]
Not sure this is useful
image
Maybe it could be a drop down to sort by protocol or just remove it all together.

**Comment by DarkGhost7** [comment]
image
Should we have another error msg when a protocol is listed on a strategy but doesn't have a protocol file? it just shows the same error as a mis-named one.

**Comment by karelianpie** [comment]
> Not sure this is useful image Maybe it could be a drop down to sort by protocol or just remove it all together.

My idea there was to immediately see what were the valid protocol names, so that if something shows up as invalid we can quickly glance over that list and see if it is indeed missing or it's just a name mismatch (e.g. `Curve Finance` - `CurveFinance`).

Happy to remove if you think this doesn't add value

**Comment by karelianpie** [comment]
> image Should we have another error msg when a protocol is listed on a strategy but doesn't have a protocol file? it just shows the same error as a mis-named one.

That is a good idea, a bit out of the scope of this work but created a new issue (https://github.com/yearn/ySync/issues/72) and will start working on it once this is merged

**Comment by karelianpie** [comment]
> Would it be possible to add a filter `Anomalies only` for the strategies ?
> 
> * Checked -> Only display the anomalies
> * Unchecked -> Display the anomalies and the good ones

Done with https://github.com/yearn/ySync/pull/71/commits/65bf3928423a5c05b2620819a13c2d53bc2829c8

**Review by DarkGhost7 — APPROVED** [review]
lgtm

**Pull request merged**
