### PR TITLE
Settings page, .env variables -> settings

### LINKED ISSUE #81: FRP: Integrate the template settings page
### What is your proposal 🚀
We need to add a settings page (like web.ycorpo.com/settings), the one available in the template repo, to be able to overwrite some stuff, and mostly yDaemon Uri in case something is down!

The [`useSettings.tsx`](https://github.com/yearn/web-lib/blob/main/packages/web-lib/contexts/useSettings.tsx) exposes a bunch of functions to be able to overwrite the defaults settings used by the app.
Every app should use `useSettings` variables instead of local constants, variables or env.

For ex, the [`YDAEMON_ENDPOINT `](https://github.com/yearn/ySync/blob/next/next.config.js#L40) env variable should ne be used, but the [`yDaemonBaseURI`](https://github.com/yearn/web-lib/blob/4638bbd2a555059c74af9d23aafeeb6b7e5d31f7/packages/web-lib/contexts/useSettings.tsx#L11) should be used instead

### What does this solve ? 🛠
Provide a better **DE**fi and way to overwrite settings if our stuff are down

### More 🔎
*N/A*

### PR DESCRIPTION
**Pull request by ai-slave**
Fixes #81

### CODE REVIEW

**Review by DarkGhost7 — DISMISSED** [review]
working well with everything hosted locally, ydaemon & ysync. Great job here

**Comment by DarkGhost7** [comment]
One thing I did notice on the settings page you cannot click the logo to go back to the main site

**Comment by ai-slave** [comment]
@DarkGhost7 Thank you, fixed this

**Comment by DarkGhost7** [comment]
Lgtm

**Review by DarkGhost7 — APPROVED** [review]
lgtm

**Pull request merged**
