### PR TITLE
feat: Add a check if every vaults want token has a description

### LINKED ISSUE #59: FRP: Add a check if every vaults want token has a token json file in tokens[network]
### What is your proposal 🚀
image
Currently there is no check if we are missing a token description for the vaults want token which should be added in data/meta/tokens[network]. This is a brand new vault and thus should show we are missing this info. 

### What does this solve ? 🛠
Making sure all data we need is added to the repo

### PR DESCRIPTION
**Pull request by karelianpie**
## Description

Check if the vault's want token has a description

## Related Issue

Closes https://github.com/yearn/ySync/issues/59

## Motivation and Context

Currently there is no check if we are missing a token description for the vaults want token

## How Has This Been Tested?

Ran locally and faked a missing `description (refer

### When description is present

Screenshot_2022-11-07_at_18_52_50

### When description is missing

Note: This was faked, this vault's want token is not really missing a description

Screenshot_2022-11-07_at_18_54_14

### CODE REVIEW

**Comment by DarkGhost7** [comment]
@karelianpie is this working for other networks as well? seems to be broken on the preview?

**Comment by karelianpie** [comment]
> @karelianpie is this working for other networks as well? seems to be broken on the preview?

@DarkGhost7 Subgraph is currently broken, I'll double check once it's back up

**Comment by DarkGhost7** [comment]
> > @karelianpie is this working for other networks as well? seems to be broken on the preview?
> 
> @DarkGhost7 Subgraph is currently broken, I'll double check once it's back up

Ok sounds good

**Comment by karelianpie** [comment]
@DarkGhost7 it seems that `token` was missing in the other networks, I've fixed that with https://github.com/yearn/ySync/pull/79/commits/c332aa91d9171d8fcadfbf12a8e93ce5e699678d

**Comment by karelianpie** [comment]
@DarkGhost7 @Majorfi is this good to be merged?

**Review by DarkGhost7 — APPROVED** [review]
lgtm

**Pull request merged**
